language: python

matrix:
  include:
      - env: TOXENV=py27
        python: '2.7'
      - env: TOXENV=py36
        python: '3.6'
      - env: TOXENV=pep8
        python: '3.6'
      - env: TOXENV=mypy
        python: '3.6'
install:
  - pip install tox
script:
  - tox
